// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyDS2bdg68QNS8uu0RmflQWwcL8bBarsGIQ',
    appId: '1:216232414413:web:2b3b69dd28e7f30b3aad84',
    messagingSenderId: '216232414413',
    projectId: 'purrbrews-meowgram',
    authDomain: 'purrbrews-meowgram.firebaseapp.com',
    storageBucket: 'purrbrews-meowgram.firebasestorage.app',
    measurementId: 'G-TYYRBL85H4',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBh6JkeCypyMQBC4HbRb1D85tWeIYj4IDU',
    appId: '1:216232414413:android:08c2ac958c0963533aad84',
    messagingSenderId: '216232414413',
    projectId: 'purrbrews-meowgram',
    storageBucket: 'purrbrews-meowgram.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyB0l-sSUGgh_f1B0RW7v_2ihiIOFZFBNFw',
    appId: '1:216232414413:ios:52f7c1e07ec0e3703aad84',
    messagingSenderId: '216232414413',
    projectId: 'purrbrews-meowgram',
    storageBucket: 'purrbrews-meowgram.firebasestorage.app',
    iosBundleId: 'com.purrbrews.meowgramClient',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyB0l-sSUGgh_f1B0RW7v_2ihiIOFZFBNFw',
    appId: '1:216232414413:ios:790c61880fc141413aad84',
    messagingSenderId: '216232414413',
    projectId: 'purrbrews-meowgram',
    storageBucket: 'purrbrews-meowgram.firebasestorage.app',
    iosBundleId: 'com.purrbrews.meowgram',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyDS2bdg68QNS8uu0RmflQWwcL8bBarsGIQ',
    appId: '1:216232414413:web:4f4c8abcbefc75f33aad84',
    messagingSenderId: '216232414413',
    projectId: 'purrbrews-meowgram',
    authDomain: 'purrbrews-meowgram.firebaseapp.com',
    storageBucket: 'purrbrews-meowgram.firebasestorage.app',
    measurementId: 'G-J824VK2P55',
  );
}
