import 'dart:convert';
import 'package:intl/intl.dart';

/// Represents a realtime chat message in meowGram.
///
/// Complies with the WebSocket wire protocol defined in Epic 1.3:
/// - [id]: Unique UUID generated by PostgreSQL.
/// - [senderId]: Authelia OIDC subject (`sub`) of the sender.
/// - [username]: Display name of the user.
/// - [textContent]: Raw message body text.
/// - [createdAt]: Timestamp recorded at PostgreSQL persistence time.
/// - [type]: Frame type ("chat", "history", "system", "error").
class ChatMessage {
  final String? id;
  final String? senderId;
  final String? username;
  final String textContent;
  final DateTime createdAt;
  final String type;

  const ChatMessage({
    this.id,
    this.senderId,
    this.username,
    required this.textContent,
    required this.createdAt,
    this.type = 'chat',
  });

  /// Backwards-compatibility getter for legacy ChatMessage callers.
  String get text => textContent;

  /// Backwards-compatibility getter for legacy ChatMessage callers.
  DateTime get timestamp => createdAt;

  /// Returns true if this message was sent by the current user with [currentSub].
  bool isFromSelf(String? currentSub) {
    if (currentSub == null || currentSub.isEmpty) return false;
    return senderId == currentSub;
  }

  /// Whether this is a system event notice (e.g. user joined/left).
  bool get isSystem => type == 'system';

  /// Whether this is an error notification from the server.
  bool get isError => type == 'error';

  /// Formatted localized time string (e.g., "6:30 PM").
  String get formattedTime {
    return DateFormat.jm().format(createdAt.toLocal());
  }

  /// Parses a WebSocket wire payload JSON map into a [ChatMessage].
  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    DateTime parsedDate;
    if (json['created_at'] != null) {
      parsedDate =
          DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now();
    } else {
      parsedDate = DateTime.now();
    }

    return ChatMessage(
      id: json['id'] as String?,
      senderId: json['sender_id'] as String?,
      username: json['username'] as String?,
      textContent: (json['text_content'] as String?) ??
          (json['text'] as String?) ??
          '',
      type: (json['type'] as String?) ?? 'chat',
      createdAt: parsedDate,
    );
  }

  /// Serializes the message to a JSON map.
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      if (senderId != null) 'sender_id': senderId,
      if (username != null) 'username': username,
      'text_content': textContent,
      'type': type,
      'created_at': createdAt.toUtc().toIso8601String(),
    };
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          textContent == other.textContent &&
          createdAt == other.createdAt &&
          type == other.type;

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      textContent.hashCode ^
      createdAt.hashCode ^
      type.hashCode;
}
