import 'package:intl/intl.dart';

/// Represents an active connected member in the presence roster broadcasted by the Hub.
class UserPresence {
  final String username;
  final String sub;
  final bool isOnline;

  const UserPresence({
    required this.username,
    required this.sub,
    this.isOnline = true,
  });

  factory UserPresence.fromJson(Map<String, dynamic> json) {
    return UserPresence(
      username: json['username'] as String? ?? 'Anonymous Cat',
      sub: json['sub'] as String? ?? '',
      isOnline: json['is_online'] as bool? ?? true,
    );
  }

  Map<String, dynamic> toJson() => {
        'username': username,
        'sub': sub,
        'is_online': isOnline,
      };

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is UserPresence &&
          runtimeType == other.runtimeType &&
          username == other.username &&
          sub == other.sub &&
          isOnline == other.isOnline;

  @override
  int get hashCode => username.hashCode ^ sub.hashCode ^ isOnline.hashCode;
}

/// Represents a realtime chat message in meowGram.
///
/// Complies with the WebSocket wire protocol defined in Epic 1.3:
/// - [id]: Unique UUID generated by PostgreSQL.
/// - [senderId]: Authelia OIDC subject (`sub`) of the sender.
/// - [username]: Display name of the user.
/// - [textContent]: Raw message body text.
/// - [createdAt]: Timestamp recorded at PostgreSQL persistence time.
/// - [type]: Frame type ("chat", "history", "system", "presence", "error").
/// - [users]: List of active connected users populated when [type] == "presence".
class ChatMessage {
  final String? id;
  final String? senderId;
  final String? username;
  final String textContent;
  final DateTime createdAt;
  final String type;
  final List<UserPresence> users;

  const ChatMessage({
    this.id,
    this.senderId,
    this.username,
    required this.textContent,
    required this.createdAt,
    this.type = 'chat',
    this.users = const [],
  });

  /// Backwards-compatibility getter for legacy ChatMessage callers.
  String get text => textContent;

  /// Backwards-compatibility getter for legacy ChatMessage callers.
  DateTime get timestamp => createdAt;

  /// Returns true if this message was sent by the current user with [currentSub].
  bool isFromSelf(String? currentSub) {
    if (currentSub == null || currentSub.isEmpty) return false;
    return senderId == currentSub;
  }

  /// Whether this is a system event notice (e.g. user joined/left).
  bool get isSystem => type == 'system';

  /// Whether this is an error notification from the server.
  bool get isError => type == 'error';

  /// Whether this is a presence roster broadcast from the Hub.
  bool get isPresence => type == 'presence';

  /// Formatted localized time string (e.g., "6:30 PM").
  String get formattedTime {
    return DateFormat.jm().format(createdAt.toLocal());
  }

  /// Parses a WebSocket wire payload JSON map into a [ChatMessage].
  factory ChatMessage.fromJson(Map<String, dynamic> json) {
    DateTime parsedDate;
    if (json['created_at'] != null) {
      parsedDate =
          DateTime.tryParse(json['created_at'].toString()) ?? DateTime.now();
    } else {
      parsedDate = DateTime.now();
    }

    final usersList = <UserPresence>[];
    if (json['users'] is List) {
      for (final item in json['users'] as List) {
        if (item is Map) {
          usersList.add(UserPresence.fromJson(Map<String, dynamic>.from(item)));
        }
      }
    }

    return ChatMessage(
      id: json['id'] as String?,
      senderId: json['sender_id'] as String?,
      username: json['username'] as String?,
      textContent: (json['text_content'] as String?) ??
          (json['text'] as String?) ??
          '',
      type: (json['type'] as String?) ?? 'chat',
      createdAt: parsedDate,
      users: usersList,
    );
  }

  /// Serializes the message to a JSON map.
  Map<String, dynamic> toJson() {
    return {
      if (id != null) 'id': id,
      if (senderId != null) 'sender_id': senderId,
      if (username != null) 'username': username,
      'text_content': textContent,
      'type': type,
      'created_at': createdAt.toUtc().toIso8601String(),
      if (users.isNotEmpty) 'users': users.map((u) => u.toJson()).toList(),
    };
  }

  @override
  bool operator ==(Object other) =>
      identical(this, other) ||
      other is ChatMessage &&
          runtimeType == other.runtimeType &&
          id == other.id &&
          senderId == other.senderId &&
          textContent == other.textContent &&
          createdAt == other.createdAt &&
          type == other.type;

  @override
  int get hashCode =>
      id.hashCode ^
      senderId.hashCode ^
      textContent.hashCode ^
      createdAt.hashCode ^
      type.hashCode;
}
